name: Check Code

on: [push, pull_request]

jobs:
  check:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        #node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Modules
      run: yarn
    - name: Check Prettier
      id: prettier
      run: yarn prettier-check
      continue-on-error: true
    - name: Run ESLint
      id: eslint
      run: yarn eslint
      continue-on-error: true
    - name: Check on failures
      if: steps.prettier.outputs.status == 'failure' || steps.eslint.outputs.status == 'failure'
      run: exit 1