name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        #node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Modules
      run: yarn
    - name: Run ESLint
      run: yarn eslint
    - name: Build
      run: yarn run build --if-present
    - name: Run Tests
      run: yarn test
      env:
        CI: true